spring:
  datasource:
    url: jdbc:mysql://rm-2zeh286g9l5sp7i76yo.mysql.rds.aliyuncs.com/spring
    name: spring
    username: myroot
    password: HangGuanLiRoot00
    driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动

server:
  port: 8009

mybatis:
  type-aliases-package: com.example.myspring.pojo
  mapper-locations: classpath:mapper/*.xml